package com.example.haystackcalculator;

public enum Operation {
    DIVISION,
    MULTIPLICATION,
    SUBTRACTION,
    SUMMATION,
    PRESSPLUS, PRESSMINUS, PRESSMULTIPLICATION, PRESSDEVISION, PRESSEQUALS, NONE
}
